# Generated by Django 5.0 on 2024-01-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_category_owner_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='category',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='owned_by',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Offer',
        ),
        migrations.DeleteModel(
            name='Owner',
        ),
    ]
