# Generated by Django 5.0 on 2024-01-22 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='room_type',
            field=models.CharField(max_length=50),
        ),
    ]
