# Generated by Django 5.0 on 2024-01-24 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_offer_location_alter_offer_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='owner',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
