# Generated by Django 5.0 on 2024-01-26 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_review_ip_remove_review_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='store.offer'),
        ),
    ]
