# Generated by Django 5.0 on 2024-01-29 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_review_rating_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
