# Generated by Django 5.0 on 2024-02-28 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
