# Generated by Django 5.0 on 2024-03-04 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
