# Generated by Django 5.0 on 2024-03-04 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_offer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='rating',
            field=models.FloatField(default=0, null=True),
        ),
    ]
