# Generated by Django 5.0 on 2024-03-11 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_owner_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='period',
            field=models.CharField(choices=[('D', 'per day'), ('W', 'per week'), ('M', 'per month')], default='D', max_length=10),
        ),
    ]
