# Generated by Django 5.0 on 2024-02-08 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name_plural': 'Views'},
        ),
    ]
