# Generated by Django 5.0 on 2024-02-08 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_viewhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'verbose_name_plural': 'views'},
        ),
    ]
