# Generated by Django 5.0 on 2024-02-20 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_alter_viewhistory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ('-view_date',), 'verbose_name_plural': 'views'},
        ),
    ]
