# Generated by Django 5.0 on 2024-03-11 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_booking_checkin_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('booking_date',)},
        ),
    ]
