# Generated by Django 5.0 on 2024-03-11 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_booking_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-booking_date',)},
        ),
    ]
